<a href="https://colab.research.google.com/github/dealbujav/CE888/blob/master/Lab_5/my_recommender(lab5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Latent Factor Models

In [0]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv", delimiter = ",", header=None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
#Droping the firt column (it only shows the number of score jokes)
df = df.drop(0,1)

###Helper function

In [0]:
arr = df.values
print(arr.shape)

(24983, 100)


In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr[idx[0][0], idx[1][0]]

7.18

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
new_arr

array([[-7.82,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ..., 99.  , 99.  ,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

##Recommender system based on latent features

In [0]:
n_latent_factors = 2

user_ratings = df.values
user_ratings
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
latent_item_features

array([[0.71192473, 0.79303534],
       [0.41833054, 0.30808855],
       [0.49959424, 0.93464942],
       [0.46871839, 0.42372297],
       [0.98740786, 0.93487315],
       [0.36531644, 0.05786519],
       [0.81758026, 0.54880252],
       [0.2353407 , 0.70130905],
       [0.72237929, 0.39604497],
       [0.89556085, 0.97307892],
       [0.01746839, 0.79638924],
       [0.6580827 , 0.67617088],
       [0.52636192, 0.63576007],
       [0.55048055, 0.32400352],
       [0.04566743, 0.98733557],
       [0.30582045, 0.85455949],
       [0.86716971, 0.68725734],
       [0.77382558, 0.72346378],
       [0.96676461, 0.57929783],
       [0.91641173, 0.71076992],
       [0.23429169, 0.16895719],
       [0.88613526, 0.79784307],
       [0.59159313, 0.76330652],
       [0.60759574, 0.92841019],
       [0.9696531 , 0.82730776],
       [0.89825467, 0.38758159],
       [0.159633  , 0.62884703],
       [0.46289548, 0.8916209 ],
       [0.42901328, 0.07367634],
       [0.04161382, 0.19283123],
       [0.

In [0]:
latent_user_preferences

array([[0.54098845, 0.46483532],
       [0.70976359, 0.65002882],
       [0.81408264, 0.55626794],
       ...,
       [0.17036022, 0.18726303],
       [0.3176437 , 0.61540089],
       [0.23926135, 0.13348658]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [0]:
sgd(30)

26.148217590720837
25.176373927107775
24.88322795640501
24.644846661065667
24.40905659452659
24.170444019180238
23.929320843991288
23.687088755294553
23.445356416994326
23.205640650869285
22.96919169020713
22.736850333921264
22.508914819985492
22.285012136243353
22.063975323663794
21.843736558163087
21.621260694412456
21.392568769042434
21.152935229411554
20.89737594885363
20.621545921497244
20.32307958366616
20.00317355090336
19.667850913128138
19.328073371606703
18.99807138348405
18.69213707863784
18.421186106827317
18.19068152092959
18.000644395810948


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.65522938e+00, -3.35493825e+00, -3.94053050e+00, ...,
        -1.33005007e+00, -3.37363167e+00, -1.15067073e+00],
       [ 2.57024074e+00,  2.80399950e+00,  2.92915789e+00, ...,
         2.37035129e+00,  2.52438256e+00,  2.59786297e+00],
       [ 4.75881788e+00,  4.71764746e+00,  4.47739413e+00, ...,
         5.54586698e+00,  3.88180329e+00,  6.39576990e+00],
       ...,
       [-1.51756810e-01, -2.25332667e-01, -2.92245205e-01, ...,
         5.97477190e-03, -2.48943051e-01,  4.66010006e-02],
       [ 7.08920597e-01,  6.31461283e-01,  5.24644285e-01, ...,
         1.00029989e+00,  4.59071753e-01,  1.19141712e+00],
       [ 2.69140519e+00,  2.62056591e+00,  2.43733277e+00, ...,
         3.25262845e+00,  2.11592577e+00,  3.77630955e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [0]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

1    ...                         100
0       (-7.82, -2.655229384136751)  ...   (99.0, -1.15067072945552)
1          (4.08, 2.57024074235365)  ...  (1.07, 2.5978629707100036)
2         (99.0, 4.758817884217778)  ...  (99.0, 6.3957699048609795)
3        (99.0, 1.3791119228857633)  ...   (99.0, 2.615613997475939)
4          (8.5, 3.514380359589229)  ...     (1.6, 4.46867907881256)
...                             ...  ...                         ...
24978     (0.44, 2.064430128676791)  ...   (7.43, 3.790545610376307)
24979     (9.13, 2.046768059892708)  ...  (8.45, 1.2187028989254112)
24980  (99.0, -0.15175680950614126)  ...  (99.0, 0.0466010006065037)
24981    (99.0, 0.7089205972107007)  ...   (99.0, 1.191417117529061)
24982     (2.43, 2.691405188816667)  ...  (99.0, 3.7763095524556727)

[24983 rows x 100 columns]

In [0]:
#MSE
error=(predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse = sum(error)/len(error)
mse

17.84839279885388

###Changing some hyper-parameters
* learning rate to 0.0005
* number of iterations to 40
* number of latent factors to 3

In [0]:
n_latent_factors2 = 3

user_ratings = df.values
user_ratings
# Initialise as random values
latent_user_preferences2 = np.random.random((user_ratings.shape[0], n_latent_factors2))
latent_item_features2 = np.random.random((user_ratings.shape[1], n_latent_factors2))

In [0]:
def predict_rating2(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference2 = latent_user_preferences2[user_id]
    item_preference2 = latent_item_features2[item_id]
    return user_preference2.dot(item_preference2)


def train2(user_id, item_id, rating, alpha=0.0005):
    
    #print item_id
    prediction_rating2 = predict_rating2(user_id, item_id)
    err =  prediction_rating2 - rating
    #print err
    user_pref_values2 = latent_user_preferences2[user_id][:]
    latent_user_preferences2[user_id] -= alpha * err * latent_item_features2[item_id]
    latent_item_features2[item_id] -= alpha * err * user_pref_values2
    return err
    

def sgd2(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences2.shape[0]):
            for item_id in range(latent_item_features2.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train2(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [0]:
sgd2(40)

24.98153316389187
24.03697439480783
23.17762322934597
22.2222536011715
20.80680313805229
19.00536622370653
17.960350787114216
17.606278384955143
17.456070091197166
17.35645509918867
17.26017997816364
17.14634509064829
17.012332256075187
16.873822634702382
16.752982382034528
16.662423909152917
16.601922544460948
16.565039840788124
16.544827897927863
16.53589831006197
16.534564520494577
16.538440450700865
16.546020856482382
16.556368920068522
16.568909107858765
16.583296307785044
16.599334731361427
16.616928040797397
16.63604897073043
16.656721324747227
16.67901007934565
16.703017023347527
16.728880347488623
16.756777162321725
16.786928238639
16.81960444865639
16.85513452294001
16.89391389595234
16.936414648321435
16.983196909042757


In [0]:
predictions2 = latent_user_preferences2.dot(latent_item_features2.T)
predictions2

array([[-2.84716768, -3.64194139, -4.96577298, ..., -2.5215958 ,
        -5.88515438, -2.54481552],
       [ 2.32126604,  4.6498051 ,  4.51685542, ...,  4.31111169,
         2.90185987,  4.97458416],
       [ 6.45468428,  5.91694293,  6.66578642, ...,  6.58677611,
         7.83923072,  6.87650684],
       ...,
       [-0.80107412,  1.2600502 ,  0.13901883, ...,  1.44114328,
        -2.37481962,  2.05188764],
       [-1.53621446, -0.4850533 , -1.8690322 , ...,  0.22063015,
        -4.02303749,  0.66116196],
       [ 3.71214993,  4.09143751,  3.96542184, ...,  4.77320259,
         3.60748723,  5.22118249]])

In [0]:
values = [zip(user_ratings[i], predictions2[i]) for i in range(predictions2.shape[0])]
comparison_data2 = pd.DataFrame(values)
comparison_data2.columns = df.columns

In [0]:
comparison_data2

1    ...                          100
0      (-7.82, -2.8471676805193202)  ...  (99.0, -2.5448155232825718)
1         (4.08, 2.321266037376194)  ...    (1.07, 4.974584158846724)
2        (99.0, 6.4546842796473385)  ...    (99.0, 6.876506842880226)
3        (99.0, 0.6434063263516346)  ...    (99.0, 6.727330444012221)
4          (8.5, 3.178630918155644)  ...     (1.6, 5.069150138748655)
...                             ...  ...                          ...
24978     (0.44, 4.067889613333735)  ...    (7.43, 6.814064895861967)
24979    (9.13, 1.1892298214945665)  ...   (8.45, 3.2150852118012407)
24980   (99.0, -0.8010741181591616)  ...    (99.0, 2.051887644879282)
24981   (99.0, -1.5362144628920122)  ...   (99.0, 0.6611619551701173)
24982    (2.43, 3.7121499317936912)  ...     (99.0, 5.22118248874437)

[24983 rows x 100 columns]

In [0]:
#MSE
error2=(predictions2[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse2 = sum(error2)/len(error2)
mse2

17.125268191162917